### PR TITLE
ListViews

### PR DESCRIPTION
**Pull request by 3lvis**
- Created the ListViews section which will hold cells, table views and collection views
- This change was partly because table view and collection views aren't necessarily part of fullscreen because a collection view might be just part of a view with other elements such as the Frontpage
- Inside each ListView type I've separated classes into: Demo, Cell, ListView and Model
- This inital PR just moves the existing ListViews (Market and GridPreview) into a separate section
- The plan is to afterwards extend ListViews to contain more types such as Favorites, YourAds, Notifications and so on

folder structure

demo app

demo views

### CODE REVIEW

**Comment by 3lvis** [comment]
💓

**Comment by axldyb** [comment]
Why all the renaming of classes? Some, `PreviewGridView` to `GridPreviewListView` for example, reads a bit strange. A preview grid sounds like a grid displaying previews. A grid preview sounds like a preview of a grid.

**Comment by axldyb** [comment]
Merged already? Ok, please note that this will cause a bunch of necessary updates to the FINN project as soon as anyone runs `carthage update`...

**Comment by 3lvis** [comment]
Could be CollectionPreviewListView and TablePreviewListView as well.

**Comment by axldyb** [comment]
The repetition of the work _view_ messes with the readability, yes, but the representation of what the classes actually does is weakened. I regret introducing the "preview" naming to begin with 😅

**Comment by 3lvis** [comment]
Other alternatives:
- AdCollectionListView and AdTableListView
- CollectionAdListView and TableAdListView

**Comment by 3lvis** [comment]
- MarketListView works fine I guess the main issue is with the preview one that has multiple ways to be represented.

**Comment by axldyb** [comment]
Well, I like the grid and table terms describing how the list views will be displayed. What are the TablePreviewListView going to be used for? Search result lists?

**Comment by 3lvis** [comment]
That's correct :)

**Comment by 3lvis** [comment]
- TablePreviewListView and GridPreviewListView
- TableAdsListView and GridAdsListView

I think the AdsListView might work better than the PreviewListView.

**Comment by axldyb** [comment]
Yeah, the idea behind the "preview" naming was to be as generic as possible. I guess that has failed a bit. May be better to use "Ad" instead.

**Comment by 3lvis** [comment]
I can try with Ad, I think it would make it easier to understand.

**Comment by ingridvf** [comment]
I have differentiated between GridView (https://zpl.io/bzym1NG), ListView (zpl.io/VkD31YG) and CardView, I'm guessing we will have them as well?

**Comment by 3lvis** [comment]
@ingridvf I wasn't able to find an example of CardView in Zeplin.

**Comment by 3lvis** [comment]
@ingridvf Those GridView, ListView and CardView have one name that represents them all?

**Comment by 3lvis** [comment]
- Recycling
  - Grid
    - MarketsGridView
    - AdsGridView
  - List
    - FavoritesListView
    - NotificationsListView
    - AdsListView

**Comment by ingridvf** [comment]
@3lvis AdView maybe?

**Pull request merged**
