### PR TITLE
Changed text field label size + Added Caption and Caption-Heavy

### PR DESCRIPTION
**Pull request by ingridvf**
# Why?

Make labels on text fields more readable

# What?

Changed size on label from Detail (12) to Caption (14). Had to add Caption and Caption Heavy to Finniverskit.

### Before
textfield before
_...._

### After
labels after
textfield after
_...._

### CODE REVIEW

**Comment by ag12** [comment]
Impressive stuff! Looks very good too me.

**Comment by ag12** [comment]
You just need to fix the test 🗡

**Comment by ingridvf** [comment]
@ag12 what, how? 😅

**Comment by ag12** [comment]
I can show you :D

**Comment by ingridvf** [comment]
Yes plz, I regret this already 🙈

**Pull request merged**
