### PR TITLE
New favorites: Draggable emptyView

### PR DESCRIPTION
**Pull request by bstien**
# Why?
When presenting the emptyView, we shouldn't disable user interaction/dragging. Was introduced in #637.

# Show me
| Before | After |
| --- | --- |
| N/A | favorites-emptyview-draggable-after |

### CODE REVIEW

**Comment by vadymmarkov** [comment]
But should it actually be possible to drag when presenting the emptyView? I think it's better when the view is static.

**Comment by bstien** [comment]
Thuy believes that it should be. I kinda agree because it provides some form of interaction.

**Comment by vadymmarkov** [comment]
That interaction doesn't really give any value, but ok. Also, at least on the gif, it looks like the movement of empty view and header view are out of sync.

**Comment by bstien** [comment]
Let's discuss this with Thuy when he's available

**Comment by bstien** [comment]
It's approved in person by @vadymmarkov🥇

**Pull request merged**
