### PR TITLE
Use normal top anchor

### PR DESCRIPTION
**Pull request by 3lvis**
I think using the normal top anchor instead of the `safeAreaLayoutGuide.topAnchor`. At least it works fine in the demo.

### CODE REVIEW

**Comment by ag12** [comment]
should we use view.compatibleTopAnchor ?

**Comment by 3lvis** [comment]
I don’t think that’s needed

**Comment by ulrikus** [comment]
I like the idea, but think we should be consistent and use it everywhere if we are to use it.

**Comment by 3lvis** [comment]
@ulrikus Not sure if I understand your comment, this PR changes to use topAnchor, which is the same thing we are doing everywhere.

**Comment by ulrikus** [comment]
I was thinking that the `compatibleTopAnchor` was a nice idea to get to utilize the `safeAreaLayoutGuide` for iOS11, but it's fine not to use it also seeing as we are some time away from supporting only iOS11.

**Comment by axldyb** [comment]
I agree to the last comment. Safe area is useful for UIViewController, but not between parent and child views.

**Pull request merged**
