### PR TITLE
Drop iOS 10

### PR DESCRIPTION
**Pull request by fespinoza**
# Why?

Because being modern and cool (also iOS 10 is from 2016).
Setting iOS 11.2 as minimum target, following the Finn app

# What?

- update the deployment target of the Demo app
- update the deployment target of the FinniversKit target
- update the podspec

### CODE REVIEW

**Comment by fespinoza** [comment]
Is there any potential issue with this @3lvis and @osanoj ?

**Comment by 3lvis** [comment]
Looks like it passed now 🤔

**Comment by 3lvis** [comment]
https://github.com/finn-no/FinniversKit/pull/532

**Comment by fespinoza** [comment]
> Looks like it passed now 🤔

I had forgotten to update the deployment target for the tests

**Pull request merged**
