### PR TITLE
Snapshot tests

### PR DESCRIPTION
**Pull request by shredlocker**
Snapshot tests for every component. Missing BroadcastContainer test. Could potentially change from using the ViewController class to making stand alone views with frames.

### CODE REVIEW

**Comment by 3lvis** [comment]
I wonder if it would make sense to just add all the snapshot tests under one file. 🤔

**Comment by 3lvis** [comment]
So it's consistent with what we're doing with Demo.swift as well.

**Comment by shredlocker** [comment]
That can be done

**Comment by 3lvis** [comment]
Much better 👌

**Pull request merged**
