### PR TITLE
Fix config file

### PR DESCRIPTION
**Pull request by AndreyMomot**
# Why?

CircleCI check failed

# What?

Fix config.yml

# Version Change

Patch

### CODE REVIEW

**Comment by BjornRuud** [comment]
The reason for the change was that the swiftlint in the docker image is really old, and it's not getting updated. The homebrew solution is the one recommended by CircleCI, but apparently some more configuration is needed.

**Comment by BjornRuud** [comment]
I'll experiment a bit on this branch. 🧐

**Comment by AndreyMomot** [comment]
Deal!
And nice that we found this

**Review by BjornRuud — APPROVED** [review]
Fixed swiftlint crash. The issue was that swiftlint does not run without a full Xcode installation, the CLI tools are not enough.

**Pull request merged**
