### PR TITLE
Cleaned podspec + added subspec DNA

### PR DESCRIPTION
**Pull request by ag12**

### CODE REVIEW

**Comment by 3lvis** [comment]
Why a subspec for DNA?

**Comment by ag12** [comment]
Experimentig, maybe even have more subspecs. Right now the though was just to use DNA for font, color and spacing. Avoid adding more files than necessary, keep it clean and simply import what’s really needed.

**Comment by 3lvis** [comment]
Not sure if we should invest in extending our CocoaPods support seeing as our plan is to get rid of it.

**Comment by ag12** [comment]
Fair enough :) 
Now that we have to, we might get the best out of it.

**Comment by ag12** [comment]
@3lvis Can we merge this? This version of .podspec is cleaner anyways.

**Comment by ag12** [comment]
Thanks 🗡💯🗡

**Pull request merged**
