### PR TITLE
Change DemoViewController to use "DismissType" and split Demo.swift into smaller files

### PR DESCRIPTION
**Pull request by 3lvis**
# Why?

We were supporting 3 ways of dismissing a component and we were solving it by adding extra initializers. This was cumbersome.

Demo.swift was getting close to reaching 400 lines of code and it was time to split it into different sections.

# What?

- Adds `DismissType` when instantiating a DemoViewController.

```swift
return DemoViewController<BasicCellDemoView>(dismissType: .dismissButton)

return KlimabroletDemoViewController(dismissType: .none)
```

- Splits `Demo.swift` into
    - `CellsDemoViews.swift`
    - `ComponentDemoViews.swift`
    - `DnaDemoViews.swift`
    - `FullscreenDemoViews.swift`
    - `RecyclingDemoViews.swift`

### CODE REVIEW

**Comment by ag12** [comment]
Thanks for your contribution. Just wondering, these PRs are they fetched from a backlog? 
Are these changes decided in the iOS recurring meeting? 
Why are you doing these changes?

**Comment by 3lvis** [comment]
Hi Amir!

>Thanks for your contribution. Just wondering, these PRs are they fetched from a backlog?
No, I'm preparing a presentation where I'll talk about FinniversKit and tried re-reading the code to understand it better and found a couple of things that could have been better.

>Are these changes decided in the iOS recurring meeting?
I haven't discussed this thing here since I just found it and it's quite small to require a big discussion.

>Why are you doing these changes?
Refer to my first answer 😄

**Comment by bstien** [comment]
Could the new and empty files be removed? I.e. `Cells.swift` and `ComponentViews.swift`. They don't seem to have a reference in the `project.pbxproj`.

**Comment by 3lvis** [comment]
@bstien Nice catch! Forgot to delete the empty files, they should be gone now. I also updated the tests.

**Pull request merged**
