### PR TITLE
removes unnecessary extension

### PR DESCRIPTION
**Pull request by shredlocker**
# Why?

After updating to Xcode 10.2 there was an error with `AVAudioSession.setCategory()`. It was previously a bug in Swift 4.2 which is now fixed with Swift 5.0

# What?

- Removed previously created extensions to work around this problem.

# Show me

No UI

### CODE REVIEW

**Comment by pimms** [comment]
Does this mean that we need to use Xcode 10.2 to build FinniversKit?

**Comment by bstien** [comment]
Seems like Travis at least needs that version😕

**Comment by shredlocker** [comment]
Things doesn't look good xD not sure what to do about this.

**Comment by osanoj** [comment]
@shredlocker Maybe downgrade to Xcode 10.1 for now, and then we can look at it more next week...

**Comment by bstien** [comment]
Guess this one is ready to be closed now, ref. #406

**Pull request closed without merging**
