### PR TITLE
Scroll login view content up if keyboard intersects input

### PR DESCRIPTION
**Pull request by henrikholmsen**
# Why?
On devices such as the iPhone 5s and 4 the keyboard will partially cover the inputs.

# What
scroll the content in the scrollview up when the keyboard appears

### CODE REVIEW

**Comment by ag12** [comment]
We have to add this to RegisterView as well. 
Maybe we could join Register and Login into a base class or something?

**Comment by henrikholmsen** [comment]
@ag12 I'll do the same with the RegisterView 👍 😊
I looked into how we could merge Register and Login, but I'm not sure if it's worth it considering the all the state handling we will have add to the "LoginAndRegisterView". The other option is to abstract the similarities of the two views ( the header text, input fields and the button) into one view, but that will still leave us with a RegistertView and a LoginView so I don't think it's worth the refactoring. It doesn't really hurt right now so I think that's something we could revisit when we start to have pain with two views 😊

**Comment by ag12** [comment]
That sounds like a good plan 👍.

**Comment by ulrikus** [comment]
Congrats with PR #100 btw! 💯🎇

**Comment by ag12** [comment]
#sugarrush 👊

**Pull request merged**
